version: '3.8'

services:
  mysql8:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - multiple-choice-questionnaires-network

  multiple-choice-questionnaires:
    container_name: multiple-choice-questionnaires
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file: ./.env
    networks:
      - multiple-choice-questionnaires-network
    depends_on:
      - mysql8
    restart: always

volumes:
  mysql-data:
  redis-data:

networks:
  multiple-choice-questionnaires-network:
    driver: bridge